# Generated by Django 4.1.5 on 2023-02-18 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25)),
                ('email', models.EmailField(max_length=254)),
                ('desig', models.CharField(max_length=25)),
                ('age', models.IntegerField()),
                ('phone', models.IntegerField()),
                ('gender', models.CharField(max_length=25)),
                ('address', models.CharField(max_length=25)),
            ],
        ),
    ]
