# Generated by Django 4.1.5 on 2023-02-18 06:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employe',
            old_name='phone',
            new_name='number',
        ),
    ]
